(function(){function wrapped_handler(it
) {
var out='\n/* Automatically generated by the serverless-wrapper-plugin */\n\nconst _handler = require(\''+(it.orig_handler_path)+'\').'+(it.handler_name)+';\nconst _wrapper = require(\''+(it.wrapper_path)+'\');\n\nmodule.exports.'+(it.handler_name)+' = function (event, context, callback) {\n  return _wrapper(_handler, event, context, callback);\n}\n';return out;
}var itself=wrapped_handler, _encodeHTML=(function(doNotSkipEncoded) {
		var encodeHTMLRules = { "&": "&#38;", "<": "&#60;", ">": "&#62;", '"': "&#34;", "'": "&#39;", "/": "&#47;" },
			matchHTML = doNotSkipEncoded ? /[&<>"'\/]/g : /&(?!#?\w+;)|<|>|"|'|\//g;
		return function(code) {
			return code ? code.toString().replace(matchHTML, function(m) {return encodeHTMLRules[m] || m;}) : "";
		};
	}());if(typeof module!=='undefined' && module.exports) module.exports=itself;else if(typeof define==='function')define(function(){return itself;});else {window.render=window.render||{};window.render['wrapped_handler']=itself;}}());